Perpustakaan/Models/DB/buku.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perpustakaan.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class buku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buku()
        {
            this.laporans = new HashSet<laporan>();
        }
    
        public int id_buku { get; set; }
        public string isbn { get; set; }
        public string judul { get; set; }
        public string penulis { get; set; }
        public string penerbit { get; set; }
        public Nullable<int> tahun { get; set; }
        public Nullable<int> stok { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<laporan> laporans { get; set; }
    }
}

Perpustakaan/Controllers/BukuController.cs
using Perpustakaan.Models.EntityManager;
using Perpustakaan.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Perpustakaan.Security;

namespace Perpustakaan.Controllers
{
    public class BukuController : Controller
    {
        // GET: Buku
        public ActionResult AddBuku()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddBuku(BukuView bv)
        {
            if (ModelState.IsValid)
            {
                BukuManager BK = new BukuManager();
                BK.AddBuku(bv);
                return RedirectToAction("Welcome", "Home");
            }
            return View();
        }
        public ActionResult ManageBukuPartial(string status = "")
        {
            //if (User.Identity.IsAuthenticated)
            //{
            string loginName = User.Identity.Name;
            BukuManager BM = new BukuManager();
            BukuDataView BDV = new BukuDataView();
            BDV.BukuProfile = BM.GetBukuData();
            string message = string.Empty;
            if (status.Equals("update"))
                message = "Update Successful";
            else if (status.Equals("delete"))
                message = "Delete Successful";
            ViewBag.Message = message;
            return PartialView(BDV);
            //}
            // return RedirectToAction("Index", "Home");
        }
        public ActionResult UpdateBukuData(int bukuID, string isbn, string
judul, string penulis, string penerbit, int tahun,int stok)
        {
            BukuView BV = new BukuView();
            BV.id_buku = bukuID;
            BV.isbn = isbn;
            BV.judul = judul;
            BV.penulis = penerbit;
            BV.penerbit = penerbit;
            BV.tahun = tahun;
            BV.stok = stok;
            BukuManager BM = new BukuManager();
            BM.UpdateBuku(BV);
            return Json(new { success = true });
        }
        public ActionResult DeleteBuku(int bukuID)
        {
            BukuManager BM = new BukuManager();
            BM.DeleteBuku(bukuID);
            return Json(new { success = true });
        }
        public ActionResult Perubahan()
        {
            return View();
        }
        [AuthorizeRoles("Librarian")]
        public ActionResult DaftarBuku()
        {
            return View();
        }
    }
}

Perpustakaan/Views/Buku/AddBuku.cshtml
@model Perpustakaan.Models.ViewModel.BukuView

@{
    ViewBag.Title = "AddBuku";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Menambah Buku</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.isbn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isbn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.isbn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.judul, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.judul, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.judul, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.penulis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.penulis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.penulis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.penerbit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.penerbit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.penerbit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tahun, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tahun, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tahun, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stok, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stok, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stok, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tambah Buku" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Main", "Index", "Home")
</div>

Perpustakaan/Views/Buku/DaftarBuku.cshtml
@{
    ViewBag.Title = "Daftar Buku";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="divUserListContainer">
    @Html.Action("ManageBukuPartial", "Buku");
</div> 
@Html.ActionLink("Tambah Buku Baru", "AddBuku", "Buku")

Perpustakaan/Views/Buku/ManageBukuPartial.cshtml
@model Perpustakaan.Models.ViewModel.BukuDataView

<div>
    <h1>Daftar Buku Perpustakaan </h1>
    <table class="table table-striped table-condensed table-hover">
        <thead>
            <tr>
                <th>ID Buku</th>
                <th>ISBN</th>
                <th>Judul</th>
                <th>Penulis</th>
                <th>Penerbit</th>
                <th>Tahun</th>
                <th>Stok</th>
                <th>Opsi</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var i in Model.BukuProfile)
            {
                <tr>
                    <td> @Html.DisplayFor(m => i.id_buku)</td>
                    <td> @Html.DisplayFor(m => i.isbn)</td>
                    <td> @Html.DisplayFor(m => i.judul)</td>
                    <td> @Html.DisplayFor(m => i.penulis)</td>
                    <td> @Html.DisplayFor(m => i.penerbit)</td>
                    <td> @Html.DisplayFor(m => i.tahun)</td>
                    <td> @Html.DisplayFor(m => i.stok)</td>
                    <td><a href="javascript:void(0)" class="lnkEdit">Edit</a></td>
                    <td><a href="javascript:void(0)" class="lnkDelete">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div id="divEdit" style="display:none">
    <input type="hidden" id="hidID" />
    <table>
        <tr>
            <td>ISBN</td>
            <td><input type="text" id="txtISBN" class="form-control" /></td>
        </tr>
        <tr>
            <td>Judul</td>
            <td><input type="text" id="txtJudul" class="form-control" /></td>
        </tr>
        <tr>
            <td>Penulis</td>
            <td><input type="text" id="txtPenulis" class="form-control" /></td>
        </tr>
        <tr>
            <td>Penerbit</td>
            <td><input type="text" id="txtPenerbit" class="form-control" /></td>
        </tr>
        <tr>
            <td>Tahun</td>
            <td><input type="text" id="txtTahun" class="form-control" /></td>
        </tr>
        <tr>
            <td>Stok</td>
            <td><input type="text" id="txtStok" class="form-control" /></td>
        </tr>
    </table>
</div>

<script type="text/javascript">
 $(function () {
 var initDialog = function (type) {
 var title = type;
 $("#divEdit").dialog({
 autoOpen: false,
 modal: true,
 title: type + ' Buku',
 width: 360,
 buttons: {
 Save: function () {
 var id = $("#hidID").val();
 var isbn = $("#txtISBN").val();
 var judul = $("#txtJudul").val();
 var penulis = $("#txtPenulis").val();
 var penerbit = $("#txtPenerbit").val();
 var tahun = $("#txtTahun").val();
 var stok = $("#txtStok").val();
 UpdateKamar(id,isbn,judul,penulis,penerbit,tahun,stok);
$(this).dialog("destroy");
 },
Cancel: function () { $(this).dialog("destroy"); }
 }
 });
 }
 function UpdateKamar(id, no, jud, lis, bit, thn,tok) {
 $.ajax({
 type: "POST",
 url: "@(Url.Action("UpdateBukuData", "Buku"))",
 data: { bukuID: id, isbn: no, judul: jud, penulis: lis,
penerbit: bit, tahun: thn,stok: tok},
 success: function (data) {

$("#divUserListContainer").load("@(Url.Action("ManageBukuPartial","Buku", new { status
="update" }))");
 },
 error: function (error) {
 //to do:
 }
 });
 }
 $("a.lnkEdit").on("click", function () {
 initDialog("Edit");
 $(".alert-success").empty();
 var row = $(this).closest('tr');
 $("#hidID").val(row.find("td:eq(0)").html().trim());
 $("#txtISBN").val(row.find("td:eq(1)").html().trim())
 $("#txtJudul").val(row.find("td:eq(2)").html().trim())
 $("#txtPenulis").val(row.find("td:eq(3)").html().trim())
 $("#txtPenerbit").val(row.find("td:eq(4)").html().trim())
 $("#txtTahun").val(row.find("td:eq(5)").html().trim())
 $("#txtStok").val(row.find("td:eq(6)").html().trim())
 $("#divEdit").dialog("open");
 return false;
 });
 function DeleteBuku(id) {
 $.ajax({
 type: "POST",
 url: "@(Url.Action("DeleteBuku","Buku"))",
 data: { bukuID: id },
 success: function (data) {

$("#divUserListContainer").load("@(Url.Action("ManageBukuPartial","Buku", new { status
="delete" }))");
 },
 error: function (error) { }
 });
 }
$("a.lnkDelete").on("click", function () {
 var row = $(this).closest('tr');
 var id = row.find("td:eq(0)").html().trim();
 var answer = confirm("Apakah anda yakin akan menghapus kamar dengan ID " + id + "?");
 if (answer)
    DeleteBuku(id);
 return false;
});
 });
</script>
<span class="alert-success">@ViewBag.Message</span>